name: staplver
description: An Incremental Backup App with Subversion.

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cross_file: ^0.3.3+6
  desktop_drop: ^0.4.4
  dotted_border: ^2.1.0
  dynamic_color: ^1.6.7
  expandable: ^5.0.1
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.3
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.3
  intl: ^0.18.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  reorderables: ^0.6.0
  riverpod_annotation: ^2.2.0
  timelines: ^0.1.0
  url_launcher: ^6.1.14
  window_manager: ^0.3.7
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  dependency_validator: 3.2.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/svn/license/
    - assets/svn/linux/
    - assets/svn/windows/

  fonts:
    - family: LINE Seed JP
      fonts:
        - asset: assets/fonts/LINESeedJP_TTF_Bd.ttf
          weight: 500
        - asset: assets/fonts/LINESeedJP_TTF_Eb.ttf
          weight: 800
